spring:
  rabbitmq:
    host: 124.238.240.172
    username: admin
    password: 123456
    port: 5672
  cloud:
    stream:
      rabbit:
        bindings:
          operateLogTopic:
            group: springboot-stream-changeDbInfo
  application:
    name: springboot-stream-changeDbInfo
server:
  port: 8080
